// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, db pull, validate) need the direct, non-pooled
    // connection — the pgbouncer pooled DATABASE_URL doesn't support what the
    // schema engine needs and causes these commands to hang. The running app
    // still uses the pooled DATABASE_URL via the driver adapter in src/utils/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
